export const metadata = {
    title: 'About || fast-next-project',
    description: 'Generated by create next app',
}

const AboutPage = () => {
    return (
        <div>
            <h1>About</h1>
        </div>
    );
};

export default AboutPage;