export const metadata = {
    title: 'Phofile || fast-next-project',
    description: 'Generated by create next app',
}

const PhofilePage = () => {
    return (
        <div>
            <h1>phofile</h1>
        </div>
    );
};

export default PhofilePage;