export const metadata = {
    title: 'Add Producat DashBoard || fast-next-project',
    description: 'Generated by create next app',
}
const AddProducatPage = () => {
    return (
        <div>
            <h1>add producat</h1>
        </div>
    );
};

export default AddProducatPage;