export const metadata = {
    title: 'DashBoard || fast-next-project',
    description: 'Generated by create next app',
}

const DashBoardPage = () => {
    return (
        <div>
            <h1>Dashboard</h1>
        </div>
    );
};

export default DashBoardPage;