import Link from "next/link";

export const metadata = {
    title: 'Blog || fast-next-project',
    description: 'Generated by create next app',
}
const blog =[
    {
        id: 1,
        year: 2000,
        title: "fast blog",
    },
    {
        id: 2,
        year: 2001,
        title: "Secend blog",
    },
    {
        id: 3,
        year: 2002,
        title: "Third blog",
    },
    {
        id: 4,
        year: 2003,
        title: "Fourd blog",
    }
]
const BlogPage = () => {
    return (
        <div>
             {
                blog.map(({id, year, title}) => <Link className=" block border border-gray-500 p-5" href={`/blog/${year}/${id}`} key={id}>{title}</Link>)
             }
        </div>
    );
};

export default BlogPage;